#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 17 17:12:35 2018

@author: jpeacock
"""

import os
import shutil
import mtpy.core.mt as mt

edi_path = r"/mnt/hgfs/MTData/MountainPass/EDI_Files_ga"
archive_path = r"/mnt/hgfs/MTData/MountainPass/Archive"

for station in os.listdir(archive_path):
    station_path = os.path.join(archive_path, station)
    if os.path.isdir(station_path):
        for fn in os.listdir(edi_path):
            if station.lower() in fn.lower():
                edi_fn = os.path.join(edi_path, fn)
                mt_obj = mt.MT(edi_fn)
                p = mt_obj.plot_mt_response(plot_num=2,
                                            plot_pt='n', 
                                            marker_size=2.2)

                p.save_plot(os.path.join(station_path, 
                                         '{0}.png'.format(station.upper())),
                            fig_dpi=600)
                shutil.copy(edi_fn, os.path.join(station_path, fn.upper()))
                print('Copied {0} to {1}'.format(fn, 
                                                 os.path.join(station_path, fn.upper())))
                break