#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 17 16:13:49 2018

@author: jpeacock
"""

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

csv_fn = r"/mnt/hgfs/MTData/MountainPass/Archive/survey_summary.csv"

s_db = pd.read_csv(csv_fn)
geometry = [Point(x, y) for x, y in zip(s_db.lon, s_db.lat)]
crs = {'init':'epsg:4326'}
s_db = s_db.drop(['lat', 'lon'], axis=1)
s_db = s_db.rename(columns={'collected_by':'operator', 
                            'nm_elev':'elev',
                            'zen_num':'instr_id'})

col_list = ['siteID', 
            'elev', 
            'hx_azm',
            'hy_azm',
            'hz_azm', 
            'hx_id', 
            'hy_id', 
            'hz_id', 
            'ex_len',
            'ey_len',
            'ex_azm',
            'ey_azm', 
            'n_chan', 
            'instr_id',
            'operator',
            'type',
            'start_date',
            'stop_date']

s_db = s_db[col_list]

g_db = gpd.GeoDataFrame(s_db, 
                        crs=crs, geometry=geometry)

g_db.to_file(r"/mnt/hgfs/jpeacock/Documents/MountainPass/Maps/mp_sites_01.shp")