# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edi_editor_test.ui'
#
# Created: Fri Apr 01 11:34:20 2016
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1092, 727)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.meta_location_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_location_edit.setObjectName(_fromUtf8("meta_location_edit"))
        self.gridLayout.addWidget(self.meta_location_edit, 6, 2, 1, 1)
        self.meta_date_label = QtGui.QLabel(self.centralwidget)
        self.meta_date_label.setObjectName(_fromUtf8("meta_date_label"))
        self.gridLayout.addWidget(self.meta_date_label, 5, 1, 1, 1)
        self.metadata = QtGui.QLabel(self.centralwidget)
        self.metadata.setObjectName(_fromUtf8("metadata"))
        self.gridLayout.addWidget(self.metadata, 0, 1, 1, 1)
        self.meta_station_label = QtGui.QLabel(self.centralwidget)
        self.meta_station_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.meta_station_label.setObjectName(_fromUtf8("meta_station_label"))
        self.gridLayout.addWidget(self.meta_station_label, 1, 1, 1, 1)
        self.meta_date_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_date_edit.setObjectName(_fromUtf8("meta_date_edit"))
        self.gridLayout.addWidget(self.meta_date_edit, 5, 2, 1, 1)
        self.meta_elev_label = QtGui.QLabel(self.centralwidget)
        self.meta_elev_label.setObjectName(_fromUtf8("meta_elev_label"))
        self.gridLayout.addWidget(self.meta_elev_label, 4, 1, 1, 1)
        self.meta_lat_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_lat_edit.setObjectName(_fromUtf8("meta_lat_edit"))
        self.gridLayout.addWidget(self.meta_lat_edit, 2, 2, 1, 1)
        self.meta_acquire_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_acquire_edit.setObjectName(_fromUtf8("meta_acquire_edit"))
        self.gridLayout.addWidget(self.meta_acquire_edit, 7, 2, 1, 1)
        self.meta_lon_label = QtGui.QLabel(self.centralwidget)
        self.meta_lon_label.setObjectName(_fromUtf8("meta_lon_label"))
        self.gridLayout.addWidget(self.meta_lon_label, 3, 1, 1, 1)
        self.meta_acquire_label = QtGui.QLabel(self.centralwidget)
        self.meta_acquire_label.setObjectName(_fromUtf8("meta_acquire_label"))
        self.gridLayout.addWidget(self.meta_acquire_label, 7, 1, 1, 1)
        self.meta_station_name_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_station_name_edit.setObjectName(_fromUtf8("meta_station_name_edit"))
        self.gridLayout.addWidget(self.meta_station_name_edit, 1, 2, 1, 1)
        self.meta_lat_label = QtGui.QLabel(self.centralwidget)
        self.meta_lat_label.setObjectName(_fromUtf8("meta_lat_label"))
        self.gridLayout.addWidget(self.meta_lat_label, 2, 1, 1, 1)
        self.meta_elev_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_elev_edit.setObjectName(_fromUtf8("meta_elev_edit"))
        self.gridLayout.addWidget(self.meta_elev_edit, 4, 2, 1, 1)
        self.meta_location_label = QtGui.QLabel(self.centralwidget)
        self.meta_location_label.setObjectName(_fromUtf8("meta_location_label"))
        self.gridLayout.addWidget(self.meta_location_label, 6, 1, 1, 1)
        self.meta_lon_edit = QtGui.QLineEdit(self.centralwidget)
        self.meta_lon_edit.setObjectName(_fromUtf8("meta_lon_edit"))
        self.gridLayout.addWidget(self.meta_lon_edit, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 2, 1)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_3.addWidget(self.progressBar, 0, 1, 1, 1)
        self.mplwidget = MatplotlibWidget(self.centralwidget)
        self.mplwidget.setMinimumSize(QtCore.QSize(900, 0))
        self.mplwidget.setObjectName(_fromUtf8("mplwidget"))
        self.gridLayout_3.addWidget(self.mplwidget, 1, 1, 7, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.static_shift_x_edit = QtGui.QLineEdit(self.centralwidget)
        self.static_shift_x_edit.setObjectName(_fromUtf8("static_shift_x_edit"))
        self.gridLayout_2.addWidget(self.static_shift_x_edit, 2, 2, 1, 1)
        self.static_shift_x_label = QtGui.QLabel(self.centralwidget)
        self.static_shift_x_label.setObjectName(_fromUtf8("static_shift_x_label"))
        self.gridLayout_2.addWidget(self.static_shift_x_label, 2, 1, 1, 1)
        self.static_shift_y_label = QtGui.QLabel(self.centralwidget)
        self.static_shift_y_label.setObjectName(_fromUtf8("static_shift_y_label"))
        self.gridLayout_2.addWidget(self.static_shift_y_label, 2, 3, 1, 1)
        self.static_shift_y_edit = QtGui.QLineEdit(self.centralwidget)
        self.static_shift_y_edit.setObjectName(_fromUtf8("static_shift_y_edit"))
        self.gridLayout_2.addWidget(self.static_shift_y_edit, 2, 4, 1, 1)
        self.static_shift_label = QtGui.QLabel(self.centralwidget)
        self.static_shift_label.setObjectName(_fromUtf8("static_shift_label"))
        self.gridLayout_2.addWidget(self.static_shift_label, 1, 1, 1, 2)
        self.static_shift_apply_button = QtGui.QPushButton(self.centralwidget)
        self.static_shift_apply_button.setObjectName(_fromUtf8("static_shift_apply_button"))
        self.gridLayout_2.addWidget(self.static_shift_apply_button, 1, 3, 1, 2)
        self.static_shift_line = QtGui.QFrame(self.centralwidget)
        self.static_shift_line.setFrameShape(QtGui.QFrame.HLine)
        self.static_shift_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.static_shift_line.setObjectName(_fromUtf8("static_shift_line"))
        self.gridLayout_2.addWidget(self.static_shift_line, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.remove_distortion_button = QtGui.QPushButton(self.centralwidget)
        self.remove_distortion_button.setObjectName(_fromUtf8("remove_distortion_button"))
        self.gridLayout_3.addWidget(self.remove_distortion_button, 3, 0, 1, 1)
        self.revert_back_button = QtGui.QPushButton(self.centralwidget)
        self.revert_back_button.setObjectName(_fromUtf8("revert_back_button"))
        self.gridLayout_3.addWidget(self.revert_back_button, 4, 0, 1, 1)
        self.save_edits_button = QtGui.QPushButton(self.centralwidget)
        self.save_edits_button.setObjectName(_fromUtf8("save_edits_button"))
        self.gridLayout_3.addWidget(self.save_edits_button, 5, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_3.addWidget(self.textEdit, 7, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem, 6, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1092, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPlot_Properties = QtGui.QMenu(self.menubar)
        self.menuPlot_Properties.setObjectName(_fromUtf8("menuPlot_Properties"))
        self.menuEDI_Information = QtGui.QMenu(self.menubar)
        self.menuEDI_Information.setObjectName(_fromUtf8("menuEDI_Information"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.plot_properties_edit = QtGui.QAction(MainWindow)
        self.plot_properties_edit.setObjectName(_fromUtf8("plot_properties_edit"))
        self.actionEdit_2 = QtGui.QAction(MainWindow)
        self.actionEdit_2.setObjectName(_fromUtf8("actionEdit_2"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionClose)
        self.menuPlot_Properties.addAction(self.plot_properties_edit)
        self.menuEDI_Information.addAction(self.actionEdit_2)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlot_Properties.menuAction())
        self.menubar.addAction(self.menuEDI_Information.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.meta_location_edit.setText(_translate("MainWindow", "None", None))
        self.meta_date_label.setText(_translate("MainWindow", "Date Collected", None))
        self.metadata.setText(_translate("MainWindow", "Metadata", None))
        self.meta_station_label.setText(_translate("MainWindow", "Station", None))
        self.meta_date_edit.setText(_translate("MainWindow", "None", None))
        self.meta_elev_label.setText(_translate("MainWindow", "Elev (m)", None))
        self.meta_lat_edit.setText(_translate("MainWindow", "0.0", None))
        self.meta_acquire_edit.setText(_translate("MainWindow", "None", None))
        self.meta_lon_label.setText(_translate("MainWindow", "Long (deg)", None))
        self.meta_acquire_label.setText(_translate("MainWindow", "Acquired By", None))
        self.meta_station_name_edit.setText(_translate("MainWindow", "None", None))
        self.meta_lat_label.setText(_translate("MainWindow", "Lat (deg)", None))
        self.meta_elev_edit.setText(_translate("MainWindow", "0.0", None))
        self.meta_location_label.setText(_translate("MainWindow", "Location", None))
        self.meta_lon_edit.setText(_translate("MainWindow", "0.0", None))
        self.static_shift_x_edit.setText(_translate("MainWindow", "1.0", None))
        self.static_shift_x_label.setText(_translate("MainWindow", "X", None))
        self.static_shift_y_label.setText(_translate("MainWindow", "Y", None))
        self.static_shift_y_edit.setText(_translate("MainWindow", "1.0", None))
        self.static_shift_label.setText(_translate("MainWindow", "Static Shift", None))
        self.static_shift_apply_button.setText(_translate("MainWindow", "Apply", None))
        self.remove_distortion_button.setText(_translate("MainWindow", "Remove Distortion", None))
        self.revert_back_button.setText(_translate("MainWindow", "Reset to Original Data", None))
        self.save_edits_button.setText(_translate("MainWindow", "Save EDI", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuPlot_Properties.setTitle(_translate("MainWindow", "Plot Properties", None))
        self.menuEDI_Information.setTitle(_translate("MainWindow", "EDI Information", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.plot_properties_edit.setText(_translate("MainWindow", "Edit", None))
        self.actionEdit_2.setText(_translate("MainWindow", "Edit", None))

from matplotlibwidget import MatplotlibWidget
