#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Wed Sep  5 17:35:07 2018

@author: jpeacock
"""

import os

read_dir = r"/media/jpeacock/My Passport/iMUSH/F012"
save_dir = r"/media/jpeacock/My Passport/iMUSH/F012_fixed"

if not os.path.exists(save_dir):
    os.mkdir(save_dir)

#### Q010
c_dict = {'HX':('hz', 'hx'),
          'HY':('hx', 'hy'),
          'HZ':('hx', 'hz'),
          'EX':('hx', 'ex'),
          'EY':('hx', 'ey')}

for fn_basename in os.listdir(read_dir):
    if fn_basename.lower().endswith('.z3d'):
        fn = os.path.join(read_dir, fn_basename)
        fn_comp = fn_basename[-6:-4].upper()
        # open and replace string
        with open(fn, 'rb') as fid:
            fn_str = fid.read()
            fn_str = fn_str.replace(c_dict[fn_comp][0].upper(),
                                    c_dict[fn_comp][1].upper())
        
        # save string
        save_fn = os.path.join(save_dir, 
                               fn_basename.replace(fn_comp.lower(), 
                                                   c_dict[fn_comp][1].upper()))
        with open(save_fn, 'wb') as sfid:
            sfid.write(fn_str)