#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 12 14:40:38 2018

@author: jpeacock
"""
import os
import datetime

import mtpy.usgs.usgs_cache as usgs

# =============================================================================
# Test collection
# =============================================================================
survey_dir = r"/mnt/hgfs/MTData/MountainPass"
save_dir = os.path.join(survey_dir, 'Archive')
if not os.path.exists(save_dir):
    os.mkdir(save_dir)

st = datetime.datetime.now()
for station in os.listdir(survey_dir):
    
    station_path = os.path.join(survey_dir, station)
    if not os.path.isdir(station_path):
        continue
    
    if '20' in station or 'EDI' in station or 'PT' in station or 'Archi' in station:
        continue
    
    zc = usgs.Z3DCollection()
    fn_list = zc.get_time_blocks(station_path)
    
    for fn_block in fn_list:
        zm = usgs.USGSasc()
        zm.get_z3d_db(fn_block)
        zm.CoordinateSystem = 'Geomagnetic North'
        zm.SurveyID = 'Mountain Pass'
        zm.read_mtft24_cfg()
        save_station_dir = os.path.join(save_dir, station)
        if not os.path.exists(save_station_dir):
            os.mkdir(save_station_dir)
        zm.write_station_info_metadata(save_dir=save_station_dir)
#        zm.write_asc_file(full=False, compress=True, 
#                          save_dir=save_station_dir)

# combine all the .cfg files into useful files
usgs_cfg_obj = usgs.USGScfg()
fn_list = usgs_cfg_obj.combine_all_station_info(save_dir)

et = datetime.datetime.now()

full_time = et-st

print(st)
print(et)
print('Took --> {0} seconds'.format(full_time.total_seconds()))
