#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Tue Jun 12 14:40:38 2018

@author: jpeacock
"""
import os
#import datetime

import mtpy.usgs.usgs_cache as usgs

# =============================================================================
# Test collection
# =============================================================================
survey_dir = r"/mnt/hgfs/MTData/iMUSH_Zen_samples/imush"

for station in os.listdir(survey_dir):
    
    station_path = os.path.join(survey_dir, station)
    if not os.path.isdir(station_path):
        continue
    
    zc = usgs.Z3DCollection()
    fn_list = zc.get_time_blocks(station_path)
    
    for fn_block in fn_list:
        zm = usgs.USGSasc()
        zm.get_z3d_db(fn_block)
#        meta_arr = zc.check_time_series(fn_block)
#        zm.fill_metadata(meta_arr)
        zm.CoordinateSystem = 'Geomagnetic North'
        zm.SurveyID = 'iMUSH'
        zm.read_mtft24_cfg()
        zm.write_station_info_metadata()
        zm.write_asc_file(full=False, compress=True)

# combine all the .cfg files into useful files
usgs_cfg_obj = usgs.USGScfg()
fn_list = usgs_cfg_obj.combine_all_station_info(survey_dir)

##station_path = r"/media/jpeacock/My Passport/iMUSH/OSU_2015/normal"
#station_path = r"/mnt/hgfs/MTData/iMUSH_Zen_samples/imush/H020"
#
#zc = usgs.Z3DCollection()
#fn_list = zc.get_time_blocks(station_path)
#
#for fn_block in fn_list:
#    zm = usgs.USGSasc()
#    meta_arr = zc.check_time_series(fn_block)
#    zm.fill_metadata(meta_arr)
#    zm.CoordinateSystem = 'Geomagnetic North'
#    zm.SurveyID = 'iMUSH'
#    zm.read_mtft24_cfg()
#    zm.write_station_info_metadata()


#st = datetime.datetime.now()
#for folder in os.listdir(station_path):
#    z3d_path = os.path.join(station_path, folder)
#    if folder in ['do_not_archive', 'png']:
#        continue
#    if os.path.isdir(z3d_path):
#        zc = usgs.Z3DCollection()
#        fn_list = zc.get_time_blocks(z3d_path)
#
#        for fn_block in fn_list:
#            zm = usgs.USGSasc()
#            meta_arr = zc.check_time_series(fn_block)
#            zm.fill_metadata(meta_arr)
#            zm.CoordinateSystem = 'Geomagnetic North'
#            zm.read_mtft24_cfg()
#            zm.write_station_info_metadata()
#    
##    zm.SurveyID = 'iMUSH'
##    zm.get_z3d_db(m_list)
##    zm.read_mtft24_cfg()
##    zm.CoordinateSystem = 'Geomagnetic North'
##    zm.SurveyID = 'iMUSH'
##    zm.write_asc_file(str_fmt='%15.7e', full=True, compress=False)
##    zm.write_station_info_metadata()
#    
#et = datetime.datetime.now()
#
#full_time = et-st
#
#print(st)
#print(et)
#print('Took --> {0} seconds'.format(full_time.total_seconds()))
#k = zc.check_time_series(m[0])
#l = zc.check_sampling_rate(k)
#db, da = zc.merge_ts(m[0])